music_dirs: ['/home/multimedia/calcifer/music']
#music_dirs: ['/home/dev/mp3']
#music_dirs: ["/home/dev/mp3", "/home/multimedia/calcifer/music/Audio Plays/Fry's English Delight - Series 3", "/home/multimedia/calcifer/music/12 Rods"]
